name: kidney_disease_classification

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  

  build-and-run-image:
    name: Build and Run Docker Image
    needs: integration
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t kidney_disease_classification:latest .

      - name: Stop and Remove Previous Container
        run: |
          docker ps -q --filter "name=kidney_disease_classification" | grep -q . && docker stop kidney_disease_classification && docker rm -fv kidney_disease_classification

      - name: Run Docker Image with Health Check
        run: |
          docker run -d -p 8080:8080 --name=kidney_disease_classification \
            --health-cmd='curl --fail http://localhost:8080/ || exit 1' \
            --health-interval=30s --health-timeout=10s --health-retries=5 \
            kidney_disease_classification:latest

      - name: Clean Previous Images and Containers
        run: |
          docker system prune -f